services:
  app:
    build: ./app
    container_name: app
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres             # Указываем имя сервиса как хост
      DB_PORT: 5432                 # Порт PostgreSQL по умолчанию
      DB_USER: andrew               # Имя пользователя PostgreSQL
      DB_PASSWORD: andrew           # Пароль пользователя PostgreSQL
      DB_NAME: timers               # Название базы данных
    depends_on:
      - postgres
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: andrew       # Замените на нужное имя пользователя
      POSTGRES_PASSWORD: andrew  # Замените на нужный пароль
      POSTGRES_DB: timers           # Замените на нужное имя базы данных
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./data/certs:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - app
    restart: unless-stopped



volumes:
  postgres_data:
    driver: local

