services:
  app:
    build: ./app
    container_name: app
    command: npm run start
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres             # Указываем имя сервиса как хост
      DB_PORT: 5432                 # Порт PostgreSQL по умолчанию
      DB_USER: andrew               # Имя пользователя PostgreSQL
      DB_PASSWORD: andrew           # Пароль пользователя PostgreSQL
      DB_NAME: timers               # Название базы данных
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: andrew       # Замените на нужное имя пользователя
      POSTGRES_PASSWORD: andrew  # Замените на нужный пароль
      POSTGRES_DB: timers           # Замените на нужное имя базы данных
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    volumes:
      - certs_data:/etc/letsencrypt
      - certs_bot:/var/www/certbot
      - /home/andrew/public:/var/www/elusha/public
    ports:
      - "80:80"   # HTTP
      - "443:443" # HTTPS
    depends_on:
      - app
    networks:
      - app-network



volumes:
  postgres_data:
  certs_data:
  certs_bot:

networks:
  app-network:
    driver: bridge
